services:
  - type: web
    name: 2k27-prom
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: GMAIL_SMTP_USERNAME
        sync: false
      - key: GMAIL_SMTP_APP_PASSWORD
        sync: false
      - key: GMAIL_SENDER_NAME
        value: 2K27 Prom
